name: CI

on: [push]

jobs:
  build_app:
    name: Build app for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            artifact_name: groundstation-app-linux-amd64-appimage
          - os: windows-latest
            artifact_name: groundstation-app-windows-msvc-amd64
          - os: macOS-latest
            artifact_name: groundstation-app-macos-amd64
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: ouuan/install-qt-action@v2.3.1 # temporary
      with:
        # Additional Qt modules to install
        modules: qtserialport
    - name: Build (*nix)
      run: |
        cd groundstation-app
        qmake groundstation-app.pro
        make
      if: matrix.os != 'windows-latest'
    - name: Prepare build environment (Windows)
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build (Windows)
      run: |
        cd groundstation-app
        qmake groundstation-app.pro -spec win32-msvc
        nmake
      if: matrix.os == 'windows-latest'
    - name: Prepare artifacts (Windows)
      run: |
        mkdir dist
        mv .\groundstation-app\release\groundstation-app.exe .\dist\groundstation.exe
        windeployqt .\dist\groundstation.exe
      if: matrix.os == 'windows-latest'
    - name: Prepare artifacts (macOS)
      run: |
        mkdir dist
        mv groundstation-app/groundstation-app.app dist/Groundstation.app
        macdeployqt dist/Groundstation.app
      if: matrix.os == 'macOS-latest'
    - name: Prepare artifacts (Linux)
      run: |
        sudo apt-get install -y libxkbcommon-x11-0
        mkdir dist
        cd groundstation-app
        make install INSTALL_ROOT=AppDir
        cd ..
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        wget -O linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy
        chmod +x *.AppImage
        cd dist
        cp ../groundstation-app/images/icon.svg ../groundstation-app.svg
        ../linuxdeploy --appdir ../groundstation-app/AppDir -e ../groundstation-app/AppDir/opt/groundstation-app/bin/groundstation-app -i ../groundstation-app.svg --create-desktop-file --plugin qt -o appimage
      if: matrix.os == 'ubuntu-latest'
    - name: Copy license and readme
      run: |
        cp LICENSE dist/
        cp README.md dist/
    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.artifact_name }}
        path: dist
  release:
    name: Create GitHub release on tag
    needs: build_app
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Get Linux artifact
        uses: actions/download-artifact@v1
        with:
          name: groundstation-app-linux-amd64-appimage
      - name: Get Windows artifact
        uses: actions/download-artifact@v1
        with:
          name: groundstation-app-windows-msvc-amd64
      - name: Get macOS artifact
        uses: actions/download-artifact@v1
        with:
          name: groundstation-app-macos-amd64
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: "TODO: write me"
          draft: true
      - name: Prepare assets
        run: |
          cd groundstation-app-linux-amd64-appimage
          zip -r all.zip *
          cd ../groundstation-app-windows-msvc-amd64
          zip -r all.zip *
          cd ../groundstation-app-macos-amd64
          zip -r all.zip *
          cd ..
          zip -r groundstation-arduino-code.zip groundstation-ino
      - name: Upload Linux release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./groundstation-app-linux-amd64-appimage/all.zip
          asset_name: groundstation-app-linux-amd64-appimage.zip
          asset_content_type: application/zip
      - name: Upload Windows release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./groundstation-app-windows-msvc-amd64/all.zip
          asset_name: groundstation-app-windows-msvc-amd64.zip
          asset_content_type: application/zip
      - name: Upload macOS release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./groundstation-app-macos-amd64/all.zip
          asset_name: groundstation-app-macos-amd64.zip
          asset_content_type: application/zip
      - name: Upload Arduino code asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./groundstation-arduino-code.zip
          asset_name: groundstation-arduino-code.zip
          asset_content_type: application/zip
