name: CI

on: [push]

jobs:
  build_app:
    name: Builds and releases groundstation app for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            artifact: groundstation-app-linux-amd64
          - os: windows-latest
            artifact: groundstation-app-windows-ia64
          - os: macOS-latest
            artifact: groundstation-app.app.zip
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0
      with:
        # Additional Qt modules to install
        modules: qtserialport
    - name: Build (*nix)
      run: |
        cd groundstation-app
        qmake groundstation-app.pro
        make qmake_all
        make
      if: matrix.os != 'windows-latest'
    - name: Prepare build environment (Windows)
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build (Windows)
      run: |
        cd groundstation-app
        qmake groundstation-app.pro -spec win32-msvc
        nmake
      if: matrix.os == 'windows-latest'
    - name: Prepare artifacts (Linux)
      run: |
        cd groundstation-app
        mv groundstation-app ../${{ matrix.artifact }}
      if: matrix.os == 'ubuntu-latest'
    - name: Prepare artifacts (macOS)
      run: |
        cd groundstation-app
        zip -r ../${{ matrix.artifact }} groundstation-app.app
      if: matrix.os == 'macOS-latest'
    - name: Prepare artifacts (Windows)
      run: |
         cd groundstation-app
         dir release
         mv release/groundstation-app.exe ../${{ matrix.artifact }}
      if: matrix.os == 'windows-latest'
    - name: Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        # File to upload to the release
        file: ${{ matrix.artifact }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: startsWith(github.ref, 'refs/tags/')

